import { Record } from '@servicenow/sdk/core'

export const ShowOutboundFields = Record({
    $id: Now.ID['up0'],
    table: 'sys_ui_policy',
    data: {
        active: true,
        conditions: 'u_direction=Outbound^EQ',
        global: true,
        inherit: false,
        isolate_script: true,
        on_load: true,
        order: 100,
        reverse_if_false: true,
        run_scripts: false,
        script_false: 'function onCondition() {\n\n}',
        script_true: 'function onCondition() {\n\n}',
        short_description: 'Show outbound fields',
        sys_domain: 'global',
        sys_domain_path: '/',
        sys_name: 'Show outbound fields',
        table: 'x_75746_ntt_ebond_u_ecase_configuration',
        ui_type: 0,
    },
})
export const ShowRESTFields = Record({
    $id: Now.ID['up1'],
    table: 'sys_ui_policy',
    data: {
        active: true,
        conditions: 'u_message_type=REST Message^EQ',
        global: true,
        inherit: false,
        isolate_script: true,
        on_load: true,
        order: 100,
        reverse_if_false: true,
        run_scripts: false,
        script_false: 'function onCondition() {\n\n}',
        script_true: 'function onCondition() {\n\n}',
        short_description: 'Show REST meesage field',
        sys_domain: 'global',
        sys_domain_path: '/',
        sys_name: 'Show REST meesage field',
        table: 'x_75746_ntt_ebond_u_ecase_configuration',
        ui_type: 0,
    },
})
export const ShowSOAPFields = Record({
    $id: Now.ID['up2'],
    table: 'sys_ui_policy',
    data: {
        active: true,
        conditions: 'u_message_type=SOAP Message^EQ',
        global: true,
        inherit: false,
        isolate_script: true,
        on_load: true,
        order: 100,
        reverse_if_false: true,
        run_scripts: false,
        script_false: 'function onCondition() {\n\n}',
        script_true: 'function onCondition() {\n\n}',
        short_description: 'Show SOAP meesage field',
        sys_domain: 'global',
        sys_domain_path: '/',
        sys_name: 'Show SOAP meesage field',
        table: 'x_75746_ntt_ebond_u_ecase_configuration',
        ui_type: 0,
    },
})
Record({
    $id: Now.ID['pa0'],
    table: 'sys_ui_policy_action',
    data: {
        cleared: false,
        disabled: 'ignore',
        field: 'u_message_type',
        field_message_type: 'none',
        mandatory: true,
        sys_name: 'u_message_type',
        table: 'x_75746_ntt_ebond_u_ecase_configuration',
        ui_policy: ShowOutboundFields.$id,
        value_action: 'ignore',
        visible: true,
    },
})
Record({
    $id: Now.ID['pa1'],
    table: 'sys_ui_policy_action',
    data: {
        cleared: false,
        disabled: 'ignore',
        field: 'u_rest_message',
        field_message_type: 'none',
        mandatory: true,
        sys_name: 'u_rest_message',
        table: 'x_75746_ntt_ebond_u_ecase_configuration',
        ui_policy: ShowRESTFields.$id,
        value_action: 'ignore',
        visible: true,
    },
})
Record({
    $id: Now.ID['pa2'],
    table: 'sys_ui_policy_action',
    data: {
        cleared: false,
        disabled: 'ignore',
        field: 'u_soap_message',
        field_message_type: 'none',
        mandatory: true,
        sys_name: 'u_soap_message',
        table: 'x_75746_ntt_ebond_u_ecase_configuration',
        ui_policy: ShowSOAPFields.$id,
        value_action: 'ignore',
        visible: true,
    },
})
